import geopandas as gpd
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


stations_list = ['SJOSC120',
                 'SJOSC119',
                 'SJOSC118',
                 'SJOSC117',
                 'SJOSC116',
                 'SJOSC115',
                 'SJO SC29',
                 'SJO SC28',
                 'SJO SC27',
                 'SJO SC26',
                 'SJO SC25',
                 'SJO SC24',
                 'SJO SC23',
                 'SJO SC22',
                 'SJO SC21',
                 'SJO SC20',
                 'SJO SC19',
                 'SJO SC18',
                 'SJO SC17',
                 'SJO SC16',
                 'SJO SC15',
                 'SJO SC14',
                 'SJO SC13',
                 'SJO SC12',
                 'SJO SC11',
                 'SJO SC10',
                 'SJO  SC9',
                 'SJO  SC8',
                 'SJO  SC7',
                 'SJO  SC1',
                 'SJO  SC2',
                 'SJO  SC3',
                 'SJO  SC4',
                 'SJO  SC5',
                 'SJO  SC6',
                 'SJO SC30',
                 'SJO SC31',
                 'SJO SC32',
                 'SJO SC33',
                 'SJO SC35',
                 'SJO SC36',
                 'SJO SC37',
                 'SJO SC38',
                 'SJO SC39',
                 'SJOSC100',
                 'SJOSC101',
                 'SJOSC102',
                 'SJOSC103',
                 'SJOSC104',
                 'SJOSC105',
                 'SJOSC106',
                 'SJOSC107',
                 'SJOSC108',
                 'SJOSC109',
                 'SJOSC110',
                 'SJOSC111',
                 'SJOSC112',
                 'SJOSC113',
                 'SJOSC114',
                 '   ABN55',
                 '   ABN54',
                 '   ABN53',
                 '   ABN52',
                 '   ABN51',
                 '   ABN50',
                 '   ABN49',
                 '   ABN48',
                 '   ABN47',
                 '   ABN46',
                 '   ABN45',
                 '   ABN44',
                 '   ABN43',
                 '   ABN42',
                 '   ABN41',
                 '   ABN40',
                 '   ABN39',
                 '   ABN38',
                 '   ABN37',
                 '   ABN36',
                 '   ABN35',
                 '   ABN34',
                 '   ABN33',
                 '   ABN32',
                 '   ABN31',
                 '   ABN30',
                 '   ABN29',
                 '   ABN28',
                 '   ABN27',
                 '   ABN26',
                 '   ABN25',
                 '   ABN24',
                 '   ABN23',
                 '   ABN22',
                 '   ABN21',
                 '   ABN20',
                 '   ABN19',
                 '   ABN18',
                 '   ABN17',
                 '   ABN16',
                 '   ABN15',
                 '   ABN14',
                 '   ABN13',
                 '   ABN12',
                 '   ABN11',
                 '   ABN10',
                 '   ABN 9',
                 '   ABN 8',
                 '   ABN 7',
                 '   ABN 6',
                 '   ABN 5',
                 '   ABN 4',
                 '   ABN 3',
                 '   ABN 2',
                 '   ABN 1']


if __name__ == "__main__":
    
    gdf = gpd.read_file("../data/geojson/calif_nev_ncei_grav.geojson")
    
    stations_in_list = [row for ix, row in gdf.iterrows() if row["station_id"] in stations_list]
    gdf_subset = pd.concat(stations_in_list, axis=0)

    fig, ax = plt.subplots()
    
    ax.scatter(gdf_subset["latitude"], gdf_subset["isostatic_anom"])
    
    fig.savefig("task2.png")